### ISSUE TITLE
树木生长机制

### ISSUE THREAD

**Issue by putianyi889** [putianyi889/TerrariaWiringTutorial#10]
用作全自动树场的效率分析（类似于用水晶碎块生成机制分析水晶碎块农场的产率）

**Comment by sgkoishi** [comment]
在每个更新帧里，如果橡树种位于任意玩家的1920 * 1.2, 1080 * 1.2范围内，那么就有1/20几率发生“试图生长”的事件。
生长结果受随机影响较大，还没仔细看...

**Comment by putianyi889** [comment]
> 在每个更新帧里，如果树木的主体部分任意方块位于任意玩家的1920 * 1.2, 1080 * 1.2范围内，那么就有1/20几率发生“试图生长”的事件。
> 越高的树木越有可能生长（疑似Bug？）。
> 生长结果受随机影响较大，还没仔细看...

希望你可以直接提交PR，纯文本、md、TeX均可，后续我可以整理到文档中。这个内容主要用作全自动树场的效率分析。

**Comment by sgkoishi** [comment]
好的，稍后我尝试整理一下树木生长相关的代码。我不是很了解TeX排版，所以内容以md为主。

**Comment by putianyi889** [comment]
https://github.com/putianyi889/TerrariaWiringTutorial/pull/16

**Comment by putianyi889** [comment]
wiki说地下红木和地上红木不同，但是 #16 并未包含此信息。

**Comment by sgkoishi** [comment]
> 
> 
> wiki说地下红木和地上红木不同，但是 #16 并未包含此信息。

看了一下，并没有找到对应地下红木的生长代码：似乎它们并不会生长？地下丛林的生成主要是各种草/藤蔓。

地下红木只有在地图生成时会出现，生长规律与其余地表树木类似。
地下红木需要纵向**12 - 22**格的空间才会生成，高度为**5 - 15**。

**Comment by putianyi889** [comment]
https://github.com/putianyi889/TerrariaWiringTutorial/releases/tag/2.9.4
