### ISSUE TITLE
Main.gfxQuality如何被赋值

### ISSUE THREAD

**Issue by putianyi889** [putianyi889/TerrariaWiringTutorial#11]
如题

**Comment by sgkoishi** [comment]
在每帧更新时被赋值，值与FPS相关（30 FPS -> 0，60 FPS -> 1）？

**Comment by putianyi889** [comment]
@sgkoishi 可以具体一点吗？FPS指画面帧率还是刷新帧率？低于30或高于60如何处理？

**Comment by sgkoishi** [comment]
> 
> 
> @sgkoishi 可以具体一点吗？FPS指画面帧率还是刷新帧率？低于30或高于60如何处理？

在更新帧（Update）内赋值，FPS以绘制帧率（Draw次数）算。值范围为0-1，低于30/高于60也只以0/1算。
至多每秒变动一次。

**Comment by putianyi889** [comment]
已更新到https://github.com/putianyi889/TerrariaWiringTutorial/releases/tag/2.9.2
