### ISSUE TITLE
未打过骷髅王的世界有没有可能生成受缚机械师？

### ISSUE THREAD

**Issue by putianyi889** [putianyi889/TerrariaWiringTutorial#28]
据WIAADC说，电路文档与wiki有矛盾。

根据电路文档，
- 地牢守卫与受缚机械师同属于地牢刷怪，
- 地牢守卫优先级更高，
- 在骷髅王前，地牢守卫刷出的概率为1，

所以地牢守卫会覆盖受缚机械师的生成。

正由WIAADC测试中。

**Comment by WilliamADCAKC** [comment]
根据实验表明：不会
地牢守卫在任何时候都会覆盖受缚机械师的生成。即使玩家位置海拔0，也不会生成受缚机械师。
